CREATE TABLE item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description TEXT,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_edit_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_date DATETIME,
    title VARCHAR(255)
);
